# model hparams                                                  
exp_meta:
    exp_name: "vispe_moco"
    log_dir: "/data/DevLearning/odme_models/logs/2023-05-28-ABC-global-gt-mask-full-dinov2b14-ft-norm"
    val_freq: 1
    batch_log_freq: 10
    seed: 12345
model_args:
    model_type: "vispe_moco"
    load_pt: False
    moco_K: 16384
    moco_T: 0.05
data_args:
    n_pts: 1
    n_neg_pts: 1
    dataset: "ABC_scene"
    batch_size: 32
    num_workers: 12
    aug_file: "local_contrastive_for_tuning.json"
optim_args:
    epochs: 2000
    learning_rate: 0.000005
    weight_decay: 0.00
    scheduler_milestones: [0.9] # at what points of total epochs
    lr_gamma: 0.1
